### ISSUE TITLE
Older GPU instance types get replaced with non-GPU instances

### ISSUE THREAD

**Issue by evahlis** [cristim/autospotting#126]
The tool works great for all instance types except the p2 family. These seem to be replaced with regular instances that have the same or higher number of CPUs and amount of RAM. Is there any configuration that needs to happen to support GPU spot instances?

**Comment by cristim** [comment]
Thanks @evahlis, welcome to the project, I'm glad you found it useful.

At the moment the instance replacement logic doesn't consider the presence and the number of GPUs when looking for compatible instance types, so your observation is as I expected, you're just the first to run into this need.

This should be relatively easy to implement, have a look at the way it's done for the other attributes in core/autoscaling.go. It would be great if you could create a PR once you have it working.

The documentation should be easy to use, but if you need assistance feel free to get in touch on gitter.

**Comment by evahlis** [comment]
Happy to give it a shot. Will keep you posted.

**Comment by cristim** [comment]
I just checked and it won't be as easy as I initially expected because we've also missing the GPU data from the instance information database.

So we first need to get it added to https://github.com/cristim/ec2-instances-info/blob/master/ec2_instance_data.go

**Comment by cristim** [comment]
Another less general but maybe also acceptable workaround may be to restrict the instance type on the group using #120, but that's a recent addition, barely tested, undocumented and reported broken by some users. 

It would be great if you could also try that out, report your findings and even fix any issues you may encounter.

**Comment by cristim** [comment]
@evahlis have you got any progress?

I can also start looking into adding support for this.

**Comment by cristim** [comment]
@evahlis I've started working on this, but it needs even more changes upstream, as you can see above.

**Comment by cristim** [comment]
@evahlis please have a look at #127, it should resolve your issue.

**Comment by cristim** [comment]
@evahlis Fix merged, thanks for reporting it!

Please test it and feel free to reopen if you notice any issues.

**Comment by evahlis** [comment]
Still getting non-GPU instances for p2.16xlarge:
`autoscaling.go:573: Launching best compatible instance: x1.16xlarge with current spot price: 1.3426`

**Comment by cristim** [comment]
@evahlis please provide more log output.

Those instances are quite expensive and I wouldn't spend my own money reproducing this with actual infrastructure.

**Comment by cristim** [comment]
I think it also needs to be added here: https://sourcegraph.com/github.com/cristim/autospotting@01d1a757c0cc5bb37b127f77b3e72c6409f216f0/-/blob/core/region.go?q=vCPU#L174-175

Working on a PR to fix this.

**Comment by cristim** [comment]
@evahlis please try to run a custom build based on 4451aae, and if you can confirm it works I'll create a PR from it.

**Comment by evahlis** [comment]
@cristim thanks. will try and let you know shortly.

**Comment by cristim** [comment]
@evahlis do you have any news?

I filed this fix as a PR in #130 so we can talk there about the testing part.

**Comment by cristim** [comment]
@evahlis I just merged the fix, please reopen if you still notice any issues.

**Comment by cristim** [comment]
I noticed issues with legacy g2 GPU instances, which are incorrectly marked as non-GPU on [ec2instances.info](http://www.ec2instances.info/?filter=p2|g2|.g3|.cg1)

This is an upstream data issue, and the only workaround so far is to change the launch configuration to use latest generation GPU instances, from the g3 and p2 families, which should be properly replaced with compatible GPU instances.

**Comment by evahlis** [comment]
Doesn't make much sense to use g2 instances anymore, but thanks for identifying the issue.

**Comment by cristim** [comment]
There's nothing we can do about this until AWS and ec2nstances.info updates the data for the G2 instance types.

We should re-open this once that's available
